[package]
name = "lsph_interactive_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
lsph = { path = "../.." }
eframe = "0.24"
egui = "0.24"
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }
