[package]
name = "lsph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.2"
geo-types = "0.7.2"
geohash = { path = "geohash" }
hashbrown = { version = "0.11.2", features = ["raw"] }
rayon = "1.5.1"

