[package]
name = "geohash"
version = "0.1.0"
authors = ["jackson211 <jackson21182@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]