[package]
name = "lsph-benches"
version = "0.0.1"
authors = ["Jackson Shi <jackson21182@gmail.com>"]

[dev-dependencies]
rand = "0.8.5"
rand_hc = "0.3.1"
criterion = { version = "0.3.5", features = ["html_reports"] }
lsph = { path = "../lsph" }

[[bench]]
name = "benchmarks"
harness = false
